export type UatEmployee = {
  name: string;
  id: string;
  role: string;
  gross: number;
  status: "Needs review" | "Blocked" | "Ready";
};

export const UAT_COMPANY = {
  id: "niva-labs-in",
  name: "Niva Labs India Pvt Ltd",
  period: "September 2026",
  employeeCount: 100,
  grossPayroll: 13604500,
  netPayable: 13011610,
  employerCost: 13784500,
} as const;

export const UAT_EMPLOYEES: UatEmployee[] = [
  { name: "Nikhil Mishra", id: "NVL-001", role: "Finance Analyst", gross: 104000, status: "Ready" },
  { name: "Aarav Joshi", id: "NVL-002", role: "Payroll Specialist", gross: 88500, status: "Ready" },
  { name: "Meera Rao", id: "NVL-003", role: "HR Executive", gross: 79000, status: "Ready" },
  { name: "Naina Chatterjee", id: "NVL-004", role: "Finance Analyst", gross: 78500, status: "Ready" },
  { name: "Rahul Chatterjee", id: "NVL-005", role: "Sales Manager", gross: 185500, status: "Ready" },
  { name: "Neha Menon", id: "NVL-006", role: "Finance Analyst", gross: 130000, status: "Ready" },
  { name: "Bhavna Khan", id: "NVL-007", role: "Senior Software Engineer", gross: 147000, status: "Ready" },
  { name: "Yash Reddy", id: "NVL-008", role: "Software Engineer", gross: 179000, status: "Ready" },
  { name: "Mohit Kulkarni", id: "NVL-009", role: "QA Engineer", gross: 115500, status: "Ready" },
  { name: "Kiran Jain", id: "NVL-010", role: "Payroll Specialist", gross: 120500, status: "Ready" },
  { name: "Diya Mishra", id: "NVL-011", role: "Senior Software Engineer", gross: 189500, status: "Ready" },
  { name: "Bhavna Sharma", id: "NVL-012", role: "Operations Executive", gross: 79500, status: "Ready" },
  { name: "Bhavna Saxena", id: "NVL-013", role: "Senior Software Engineer", gross: 149000, status: "Ready" },
  { name: "Vikram Gupta", id: "NVL-014", role: "Finance Analyst", gross: 112000, status: "Ready" },
  { name: "Priya Patel", id: "NVL-015", role: "Account Executive", gross: 144000, status: "Ready" },
  { name: "Farhan Jain", id: "NVL-016", role: "QA Engineer", gross: 134000, status: "Ready" },
  { name: "Aditi Joshi", id: "NVL-017", role: "Product Designer", gross: 156000, status: "Needs review" },
  { name: "Neha Sharma", id: "NVL-018", role: "Operations Executive", gross: 73500, status: "Ready" },
  { name: "Pranav Verma", id: "NVL-019", role: "Sales Manager", gross: 196000, status: "Ready" },
  { name: "Gaurav Singh", id: "NVL-020", role: "Senior Software Engineer", gross: 187500, status: "Ready" },
  { name: "Vikram Menon", id: "NVL-021", role: "Account Executive", gross: 122500, status: "Ready" },
  { name: "Tanvi Iyer", id: "NVL-022", role: "HR Executive", gross: 73500, status: "Ready" },
  { name: "Zoya Verma", id: "NVL-023", role: "Product Manager", gross: 230000, status: "Ready" },
  { name: "Meera Menon", id: "NVL-024", role: "Senior Software Engineer", gross: 181500, status: "Ready" },
  { name: "Pranav Gupta", id: "NVL-025", role: "Payroll Specialist", gross: 96500, status: "Ready" },
  { name: "Yash Menon", id: "NVL-026", role: "HR Executive", gross: 87000, status: "Ready" },
  { name: "Akash Bansal", id: "NVL-027", role: "Finance Analyst", gross: 127000, status: "Ready" },
  { name: "Diya Gupta", id: "NVL-028", role: "Payroll Specialist", gross: 81500, status: "Ready" },
  { name: "Vikram Joshi", id: "NVL-029", role: "Finance Analyst", gross: 128500, status: "Ready" },
  { name: "Arjun Sharma", id: "NVL-030", role: "Product Manager", gross: 145500, status: "Ready" },
  { name: "Nikhil Mehta", id: "NVL-031", role: "Senior Software Engineer", gross: 155000, status: "Ready" },
  { name: "Aditi Singh", id: "NVL-032", role: "Software Engineer", gross: 128000, status: "Ready" },
  { name: "Farhan Desai", id: "NVL-033", role: "Software Engineer", gross: 177000, status: "Ready" },
  { name: "Kavya Kulkarni", id: "NVL-034", role: "QA Engineer", gross: 122000, status: "Ready" },
  { name: "Varun Chatterjee", id: "NVL-035", role: "Operations Executive", gross: 63500, status: "Ready" },
  { name: "Sahil Patel", id: "NVL-036", role: "Software Engineer", gross: 158000, status: "Ready" },
  { name: "Kabir Rao", id: "NVL-037", role: "Sales Manager", gross: 233500, status: "Ready" },
  { name: "Shreya Joshi", id: "NVL-038", role: "Account Executive", gross: 131500, status: "Ready" },
  { name: "Sahil Jain", id: "NVL-039", role: "Operations Executive", gross: 97500, status: "Ready" },
  { name: "Pooja Kulkarni", id: "NVL-040", role: "QA Engineer", gross: 90500, status: "Ready" },
  { name: "Yash Jain", id: "NVL-041", role: "Account Executive", gross: 126000, status: "Ready" },
  { name: "Pooja Sharma", id: "NVL-042", role: "HR Executive", gross: 99000, status: "Blocked" },
  { name: "Aditi Shah", id: "NVL-043", role: "Sales Manager", gross: 192000, status: "Ready" },
  { name: "Ishita Khan", id: "NVL-044", role: "Operations Executive", gross: 79000, status: "Ready" },
  { name: "Pranav Sharma", id: "NVL-045", role: "Product Manager", gross: 220000, status: "Ready" },
  { name: "Nikhil Reddy", id: "NVL-046", role: "QA Engineer", gross: 99500, status: "Ready" },
  { name: "Meera Iyer", id: "NVL-047", role: "Software Engineer", gross: 110000, status: "Ready" },
  { name: "Tanvi Mehta", id: "NVL-048", role: "Product Manager", gross: 148500, status: "Ready" },
  { name: "Vikram Khan", id: "NVL-049", role: "Software Engineer", gross: 93000, status: "Ready" },
  { name: "Sahil Verma", id: "NVL-050", role: "Product Manager", gross: 204000, status: "Ready" },
  { name: "Rohan Nair", id: "NVL-051", role: "Account Executive", gross: 104500, status: "Ready" },
  { name: "Dev Iyer", id: "NVL-052", role: "Senior Software Engineer", gross: 212500, status: "Ready" },
  { name: "Pooja Iyer", id: "NVL-053", role: "Senior Software Engineer", gross: 220500, status: "Ready" },
  { name: "Ananya Sharma", id: "NVL-054", role: "Product Manager", gross: 203500, status: "Ready" },
  { name: "Akash Gupta", id: "NVL-055", role: "Sales Manager", gross: 196000, status: "Ready" },
  { name: "Naina Saxena", id: "NVL-056", role: "QA Engineer", gross: 100000, status: "Ready" },
  { name: "Vikram Mehta", id: "NVL-057", role: "HR Executive", gross: 102500, status: "Ready" },
  { name: "Rhea Kapoor", id: "NVL-058", role: "Senior Software Engineer", gross: 208500, status: "Ready" },
  { name: "Rahul Menon", id: "NVL-059", role: "Account Executive", gross: 101500, status: "Ready" },
  { name: "Aarav Rao", id: "NVL-060", role: "Finance Analyst", gross: 105500, status: "Ready" },
  { name: "Aditi Desai", id: "NVL-061", role: "Senior Software Engineer", gross: 150000, status: "Ready" },
  { name: "Tanvi Jain", id: "NVL-062", role: "Software Engineer", gross: 93000, status: "Ready" },
  { name: "Kiran Verma", id: "NVL-063", role: "QA Engineer", gross: 148500, status: "Needs review" },
  { name: "Aarav Khan", id: "NVL-064", role: "Software Engineer", gross: 101000, status: "Ready" },
  { name: "Nikhil Singh", id: "NVL-065", role: "QA Engineer", gross: 104000, status: "Ready" },
  { name: "Shreya Patel", id: "NVL-066", role: "Product Designer", gross: 153000, status: "Ready" },
  { name: "Neha Joshi", id: "NVL-067", role: "Product Manager", gross: 192500, status: "Ready" },
  { name: "Dev Menon", id: "NVL-068", role: "Finance Analyst", gross: 105500, status: "Ready" },
  { name: "Sneha Nair", id: "NVL-069", role: "Senior Software Engineer", gross: 216000, status: "Ready" },
  { name: "Kavya Singh", id: "NVL-070", role: "HR Executive", gross: 88500, status: "Ready" },
  { name: "Yash Sharma", id: "NVL-071", role: "Account Executive", gross: 169000, status: "Ready" },
  { name: "Dev Jain", id: "NVL-072", role: "QA Engineer", gross: 124000, status: "Ready" },
  { name: "Ananya Khan", id: "NVL-073", role: "Software Engineer", gross: 166000, status: "Ready" },
  { name: "Pooja Joshi", id: "NVL-074", role: "Operations Executive", gross: 80500, status: "Ready" },
  { name: "Varun Reddy", id: "NVL-075", role: "Finance Analyst", gross: 106000, status: "Ready" },
  { name: "Rhea Verma", id: "NVL-076", role: "HR Executive", gross: 73500, status: "Ready" },
  { name: "Sana Sharma", id: "NVL-077", role: "QA Engineer", gross: 89000, status: "Ready" },
  { name: "Kabir Mehta", id: "NVL-078", role: "Product Manager", gross: 214500, status: "Ready" },
  { name: "Mohit Chatterjee", id: "NVL-079", role: "Operations Executive", gross: 81500, status: "Ready" },
  { name: "Ananya Joshi", id: "NVL-080", role: "QA Engineer", gross: 98500, status: "Ready" },
  { name: "Siddharth Singh", id: "NVL-081", role: "Finance Analyst", gross: 123000, status: "Ready" },
  { name: "Sneha Rao", id: "NVL-082", role: "Software Engineer", gross: 150000, status: "Ready" },
  { name: "Rohan Sharma", id: "NVL-083", role: "Senior Software Engineer", gross: 219500, status: "Ready" },
  { name: "Farhan Mehta", id: "NVL-084", role: "Sales Manager", gross: 181000, status: "Ready" },
  { name: "Meera Das", id: "NVL-085", role: "Software Engineer", gross: 127000, status: "Ready" },
  { name: "Aarav Shah", id: "NVL-086", role: "Finance Analyst", gross: 120500, status: "Ready" },
  { name: "Rhea Iyer", id: "NVL-087", role: "Product Manager", gross: 151500, status: "Ready" },
  { name: "Tanvi Rao", id: "NVL-088", role: "Operations Executive", gross: 104000, status: "Ready" },
  { name: "Rohan Gupta", id: "NVL-089", role: "QA Engineer", gross: 124500, status: "Ready" },
  { name: "Sneha Bansal", id: "NVL-090", role: "Account Executive", gross: 126500, status: "Ready" },
  { name: "Siddharth Khan", id: "NVL-091", role: "Operations Executive", gross: 102000, status: "Ready" },
  { name: "Vikram Rao", id: "NVL-092", role: "Senior Software Engineer", gross: 179500, status: "Ready" },
  { name: "Sana Mehta", id: "NVL-093", role: "HR Executive", gross: 73500, status: "Ready" },
  { name: "Kabir Patel", id: "NVL-094", role: "Sales Manager", gross: 186000, status: "Ready" },
  { name: "Shreya Sharma", id: "NVL-095", role: "Finance Analyst", gross: 101000, status: "Ready" },
  { name: "Aditi Rao", id: "NVL-096", role: "QA Engineer", gross: 99500, status: "Ready" },
  { name: "Arjun Menon", id: "NVL-097", role: "Software Engineer", gross: 141500, status: "Ready" },
  { name: "Ananya Singh", id: "NVL-098", role: "Product Manager", gross: 230000, status: "Ready" },
  { name: "Dev Sharma", id: "NVL-099", role: "Operations Executive", gross: 103000, status: "Ready" },
  { name: "Shreya Iyer", id: "NVL-100", role: "Senior Software Engineer", gross: 152000, status: "Ready" }
];
