"use client";

import { Bot, Check, ChevronRight, CircleHelp, Download, FileText, IndianRupee, LayoutDashboard, LockKeyhole, Menu, Search, ShieldCheck, Sparkles, TriangleAlert, Users, X } from "lucide-react";
import { useMemo, useState } from "react";

type View = "overview" | "payroll" | "employees" | "compliance" | "reports";
type Issue = { id:number; employee:string; issue:string; severity:"High"|"Blocker"|"Medium"; value:string; resolved:boolean };
const cash = new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
const nav = [{id:"overview",label:"Overview",icon:LayoutDashboard},{id:"payroll",label:"Payroll runs",icon:IndianRupee},{id:"employees",label:"Employees",icon:Users},{id:"compliance",label:"Compliance",icon:ShieldCheck},{id:"reports",label:"Reports",icon:FileText}] as const;
const people = [{name:"Aarav Mehta",id:"ACM-001",role:"Product Lead",gross:184200,status:"Needs review"},{name:"Meera Nair",id:"ACM-002",role:"Engineering Manager",gross:226500,status:"Blocked"},{name:"Rohan Das",id:"ACM-003",role:"Senior Designer",gross:142000,status:"Needs review"},{name:"Ishita Shah",id:"ACM-004",role:"Finance Manager",gross:165000,status:"Ready"},{name:"Kabir Singh",id:"ACM-005",role:"Software Engineer",gross:128000,status:"Ready"}];

export default function Home(){
 const [view,setView]=useState<View>("overview"),[menu,setMenu]=useState(false),[assistant,setAssistant]=useState(true),[query,setQuery]=useState(""),[selected,setSelected]=useState<Issue|null>(null),[toast,setToast]=useState(""),[status,setStatus]=useState("Draft");
 const [issues,setIssues]=useState<Issue[]>([{id:1,employee:"Aarav Mehta",issue:"Net pay changed by 31%",severity:"High",value:"+₹48,200",resolved:false},{id:2,employee:"Meera Nair",issue:"Professional Tax location missing",severity:"Blocker",value:"Review",resolved:false},{id:3,employee:"Rohan Das",issue:"Loss of pay exceeds attendance input",severity:"Medium",value:"3 days",resolved:false}]);
 const [answer,setAnswer]=useState("I found three items that need review. Meera’s missing work location blocks the Professional Tax calculation.");
 const open=issues.filter(x=>!x.resolved).length, blockers=issues.filter(x=>!x.resolved&&x.severity==="Blocker").length;
 const filtered=useMemo(()=>people.filter(p=>`${p.name} ${p.id} ${p.role}`.toLowerCase().includes(query.toLowerCase())),[query]);
 const notify=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(""),2400)};
 const go=(next:View)=>{setView(next);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
 const resolve=()=>{if(!selected)return;setIssues(xs=>xs.map(x=>x.id===selected.id?{...x,resolved:true}:x));setSelected(null);notify("Exception resolved and audit trail updated.")};
 const submit=()=>{if(open){notify(`Resolve ${open} exception${open===1?"":"s"} first.`);return}setStatus("Submitted");notify("Payroll submitted for approval.")};
 const ask=(label:string)=>{const a:Record<string,string>={"Explain net-pay changes":"Aarav’s increase is a ₹42,000 bonus plus ₹6,200 arrears. Review both source inputs before clearing it.","Show blocking issues":blockers?"Meera Nair has no work location, so the Professional Tax rule cannot be selected safely.":"No blocking issues remain. Clear the remaining review items before approval.","Compare with August":"September gross payroll is 3.8% higher, driven by six bonuses and two new joiners."};setAnswer(a[label]);setAssistant(true)};
 const download=(name:string)=>{const csv="Employee ID,Employee,Gross Pay,Status\n"+people.map(p=>`${p.id},${p.name},${p.gross},${p.status}`).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`${name.toLowerCase().replaceAll(" ","-")}-sep-2026.csv`;a.click();URL.revokeObjectURL(a.href);notify(`${name} downloaded.`)};
 return <main className="product-shell"><aside className={`sidebar ${menu?"mobile-open":""}`}><div className="brand"><span className="brand-mark">प</span><span>Payroll OS</span><button className="close-nav" onClick={()=>setMenu(false)} aria-label="Close"><X/></button></div><div className="company-switch"><span className="company-logo">AC</span><span><strong>Acme Labs</strong><small>September 2026</small></span></div><nav>{nav.map(({id,label,icon:Icon})=><button key={id} className={`nav-item ${view===id?"active":""}`} onClick={()=>go(id)}><Icon/>{label}</button>)}</nav><div className="sidebar-foot"><LockKeyhole/>Representative UAT data</div></aside>{menu&&<button className="nav-backdrop" onClick={()=>setMenu(false)} aria-label="Close navigation"/>}<section className="workspace"><header className="topbar"><div><button className="mobile-menu" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu/></button><span className="eyebrow">Payroll workspace</span></div><div className="top-actions"><button className="icon-button" onClick={()=>notify("Help centre is planned for secure UAT.")}><CircleHelp/></button><span className="avatar">AS</span></div></header><div className="content">
 {view==="overview"&&<Overview issues={issues} open={open} status={status} go={go} select={setSelected} assistant={assistant} setAssistant={setAssistant} answer={answer} ask={ask}/>}
 {view==="payroll"&&<Payroll issues={issues} open={open} status={status} select={setSelected} submit={submit}/>}
 {view==="employees"&&<Employees people={filtered} query={query} setQuery={setQuery} notify={notify}/>}
 {view==="compliance"&&<Compliance notify={notify}/>}
 {view==="reports"&&<Reports download={download}/>}
 </div></section>{selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><span className="section-label">Payroll exception</span><h2>{selected.employee}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}><X/></button></div><span className={`issue-pill ${selected.severity.toLowerCase()}`}>{selected.severity}</span><h3>{selected.issue}</h3><p>{selected.severity==="Blocker"?"Apply Karnataka as the work location to select the configured Professional Tax rule. This demonstration records the decision without changing real payroll data.":"Source inputs have been reconciled with August. Confirm to clear this item from the demonstration run."}</p><div className="modal-actions"><button className="secondary-action" onClick={()=>setSelected(null)}>Cancel</button><button className="primary-action" onClick={resolve}><Check/>Confirm and resolve</button></div></section></div>}{toast&&<div className="toast" role="status"><Check/>{toast}</div>}</main>
}

function Title({title,copy,action}:{title:string;copy:string;action?:React.ReactNode}){return <div className="title-row"><div><h1>{title}</h1><p>{copy}</p></div>{action}</div>}
function Progress({open,status}:{open:number;status:string}){const ready=open===0;return <section className="run-panel"><div className="panel-heading"><div><span className="section-label">Current run</span><h2>Monthly payroll · Sep 2026</h2></div><span className={`status-badge ${status==="Submitted"?"submitted":""}`}>{status}</span></div><div className="run-progress"><Step n="1" name="Inputs" note="84 employees" state="complete"/><Line done/><Step n="2" name="Validation" note={`${open} exceptions`} state={ready?"complete":"current"}/><Line done={ready}/><Step n="3" name="Approval" note={status==="Submitted"?"Submitted":"Not submitted"} state={ready?"current":""}/><Line done={status==="Submitted"}/><Step n="4" name="Finalize" note="Outputs locked" state=""/></div></section>}
function Step({n,name,note,state}:{n:string;name:string;note:string;state:string}){return <div className={`progress-step ${state}`}><span>{n}</span><strong>{name}</strong><small>{note}</small></div>};function Line({done=false}:{done?:boolean}){return <div className={`progress-line ${done?"complete":""}`}/>}
function IssueList({issues,select,all}:{issues:Issue[];select:(x:Issue)=>void;all?:()=>void}){return <div className="exceptions-panel"><div className="panel-heading"><div><span className="section-label">Needs attention</span><h2>Payroll exceptions</h2></div>{all&&<button className="text-action" onClick={all}>View all</button>}</div><div className="exception-list">{issues.map(x=><button className={`exception-row ${x.resolved?"resolved":""}`} key={x.id} onClick={()=>!x.resolved&&select(x)}><span className={`severity ${x.resolved?"done":x.severity.toLowerCase()}`}>{x.resolved?<Check/>:<TriangleAlert/>}</span><span className="exception-copy"><strong>{x.employee}</strong><small>{x.resolved?"Resolved":x.issue}</small></span><span className="exception-value">{x.resolved?"Cleared":x.value}</span><ChevronRight/></button>)}</div></div>}
function Overview({issues,open,status,go,select,assistant,setAssistant,answer,ask}:any){const stats=[{label:"Employees",value:"84",note:`${84-open} ready · ${open} need review`},{label:"Gross payroll",value:cash.format(6842500),note:"+3.8% from August"},{label:"Net payable",value:cash.format(5526140),note:"Draft calculation"},{label:"Employer cost",value:cash.format(7218940),note:"Includes employer PF"}];return <><Title title="September payroll" copy="Review the draft, resolve exceptions and submit it for approval." action={<button className="primary-action" onClick={()=>go("payroll")}>Review payroll <ChevronRight/></button>}/><div className="uat-notice"><ShieldCheck/><span><strong>Interactive product preview</strong>Actions use representative data and reset when reloaded.</span></div><section className="stat-grid">{stats.map(x=><article className="stat-card" key={x.label}><div className="stat-head"><span>{x.label}</span></div><strong>{x.value}</strong><small>{x.note}</small></article>)}</section><Progress open={open} status={status}/><section className="lower-grid"><IssueList issues={issues} select={select} all={()=>go("payroll")}/><div className="copilot-panel"><div className="copilot-head"><span><Sparkles/>Payroll Copilot</span><button onClick={()=>setAssistant(!assistant)}>{assistant?"Hide":"Open"}</button></div>{assistant&&<div className="copilot-body"><div className="assistant-message"><Bot/><p>{answer}</p></div><div className="quick-actions">{["Explain net-pay changes","Show blocking issues","Compare with August"].map(x=><button key={x} onClick={()=>ask(x)}>{x}</button>)}</div><small className="ai-note"><LockKeyhole/>Copilot explains data. It cannot approve payroll.</small></div>}</div></section></>}
function Payroll({issues,open,status,select,submit}:any){return <><Title title="Payroll runs" copy="Validate September payroll and move it through controlled approval." action={<button className="primary-action" onClick={submit}>{status==="Submitted"?<><Check/>Submitted</>:<>Submit for approval <ChevronRight/></>}</button>}/><div className="summary-strip"><span><strong>Sep 2026</strong><small>Monthly · 84 employees</small></span><span><strong>{cash.format(6842500)}</strong><small>Gross payroll</small></span><span><strong>{open}</strong><small>Open exceptions</small></span><span><strong>{status}</strong><small>Run status</small></span></div><Progress open={open} status={status}/><div className="full-panel"><IssueList issues={issues} select={select}/></div></>}
function Employees({people,query,setQuery,notify}:any){return <><Title title="Employees" copy="Review payroll readiness and employee compensation inputs." action={<button className="primary-action" onClick={()=>notify("Employee onboarding is in the next product increment.")}>Add employee</button>}/><div className="toolbar"><label className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, ID or role"/></label><span>84 employees · 82 ready</span></div><div className="table-card"><table><thead><tr><th>Employee</th><th>Role</th><th>Monthly gross</th><th>Payroll status</th></tr></thead><tbody>{people.map((p:any)=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.id}</small></td><td>{p.role}</td><td>{cash.format(p.gross)}</td><td><span className={`employee-status ${p.status.toLowerCase().replace(" ","-")}`}>{p.status}</span></td></tr>)}</tbody></table>{!people.length&&<div className="empty-state">No employees match your search.</div>}</div></>}
function Compliance({notify}:any){const rows=[{title:"Provident Fund",due:"15 Oct 2026",status:"Ready",copy:"82 eligible employees · ECR inputs validated"},{title:"ESI contribution",due:"15 Oct 2026",status:"Ready",copy:"18 eligible employees · contribution reconciled"},{title:"Professional Tax",due:"20 Oct 2026",status:"Blocked",copy:"1 employee work location requires review"},{title:"TDS deposit",due:"07 Oct 2026",status:"Review",copy:"Monthly deduction register prepared"}];return <><Title title="Compliance" copy="Track statutory readiness from the same controlled payroll run."/><div className="compliance-grid">{rows.map(x=><article className="compliance-card" key={x.title}><div><ShieldCheck/><span className={`employee-status ${x.status.toLowerCase()}`}>{x.status}</span></div><h2>{x.title}</h2><p>{x.copy}</p><small>Due {x.due}</small><button className="secondary-action" onClick={()=>notify(`${x.title} detail opened for representative data.`)}>Review details <ChevronRight/></button></article>)}</div></>}
function Reports({download}:any){const rows=["Payroll register","Bank advice","TDS deduction register","Variance report"];return <><Title title="Reports" copy="Generate controlled outputs from the September payroll draft."/><div className="report-list">{rows.map(x=><article className="report-row" key={x}><span className="report-icon"><FileText/></span><span><strong>{x}</strong><small>Representative September payroll output</small></span><span className="file-tag">CSV</span><button className="secondary-action" onClick={()=>download(x)}><Download/>Download</button></article>)}</div><div className="security-note"><LockKeyhole/><span><strong>Representative output only</strong><small>Downloads are not statutory filings or bank instructions.</small></span></div></>}
